cargo: Update dependencies
Need to update this crate to be compatible with recent Rust toolchains.

Tested: Verified I can generate a Bitbake recipe from my Rust project with a new toolchain

```
$ rustup ...
$ cargo --version
cargo 1.83.0 (5ffbef321 2024-10-29)
$ rustc --version
rustc 1.83.0 (90b35a623 2024-11-26)
$ git checkout https://github.com/meta-rust/cargo-bitbake
$ cd cargo-bitbake
$ cargo install --path .
$ cd ~
$ git checkout https://github.com/peterdelevoryas/dbus-sensors -b cargo-rust
$ cd dbus-sensors
```

Before:

```
$ cargo bitbake
error: failed to parse lock file at: /home/pdel/openbmc/dbus-sensors/Cargo.lock

Caused by:
  lock file version `4` was found, but this version of Cargo does not understand this lock file, perhaps Cargo needs to be updated?
```

After:

```
$ cargo bitbake
No package.description set in your Cargo.toml, using package.name
No package.homepage set in your Cargo.toml, trying package.repository
No package.license set in your Cargo.toml, trying package.license_file
No package.license_file set in your Cargo.toml
Assuming CLOSED license
Wrote: dbus-sensors_0.1.0.bb
```

Signed-off-by: Peter Delevoryas <peter@pjd.dev>